# 기본 설정 (Docker 환경에서 사용)
server:
  port: 8080

spring:
  application:
    name: qna
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    hibernate:
      ddl-auto: none # Firestore를 사용하므로 JPA 스키마 생성 비활성화
    properties:
      hibernate:
        show_sql: true
        format_sql: true

# Firebase 설정
firebase:
  secret-id: "firebase-adminsdk"
  project-id: "aivle-team0721" # 실제 프로젝트 ID
  storage-bucket: "aivle-team0721.firebasestorage.app" # Storage 버킷 이름 추가

logging:
  level:
    org.springframework.cloud: debug

management:
  endpoints:
    web:
      cors:
        allowed-origins: "*"
        allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
        allowed-headers: "*"

---

# 로컬 개발 환경 (default profile)
spring:
  profiles: default

server:
  port: 8086 # 로컬 개발용 포트

---

# Docker 환경 (docker profile)
spring:
  profiles: docker
# Docker 환경에서는 기본 포트인 8080이 사용됩니다.