server:
  port: 8088

# Firebase 설정
firebase:
  service-account-file: "src/main/resources/firebase-adminsdk.json"
  database-url: "aivle-team0721" # 실제 프로젝트 ID로 변경해주세요

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: ai
          uri: http://localhost:8082
          predicates:
            - Path=/ais/**, 
        - id: term
          uri: http://localhost:8083
          predicates:
            - Path=/terms/**, /getTerms/**
        - id: point
          uri: http://localhost:8085
          predicates:
            - Path=/points/**, /getPoints/**, /api/points/**
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
              - "X-Authenticated-User-Uid"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: ai
          uri: http://ai:8080
          predicates:
            - Path=/ais/**, 
        - id: term
          uri: http://term:8080
          predicates:
            - Path=/terms/**, 
        - id: point
          uri: http://point:8080
          predicates:
            - Path=/points/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
              - "X-Authenticated-User-Uid"
            allowCredentials: true

server:
  port: 8080
