server:
  port: 8080

spring:
  application:
    name: term

# Firebase 설정
firebase:
  service-account-file: "file:src/main/resources/firebase-adminsdk.json"
  project-id: "aivle-team0721" # 실제 프로젝트 ID로 변경해주세요

---

spring:
  profiles: default
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: term
#<<< EDA / Topic Name
          destination: self
#>>> EDA / Topic Name
          contentType: application/json
        event-out:
#<<< EDA / Topic Name
          destination: self
#>>> EDA / Topic Name
          contentType: application/json

logging:
  level:
    org.springframework.cloud: debug


server:
  port: 8083

---

spring:
  profiles: docker
  cloud:
    stream:
      kafka:
        binder:
          brokers: my-kafka:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: term
          destination: self
          contentType: application/json
        event-out:
          destination: self
          contentType: application/json


