server:
  port: 8085

spring:
  application:
    name: point

# Firebase 설정
firebase:
  service-account-file: "file:src/main/resources/firebase-adminsdk.json"
  project-id: "aivle-team0721" # 실제 프로젝트 ID로 변경해주세요

---

spring:
  profiles: default
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: point
#<<< EDA / Topic Name
          destination: self
#>>> EDA / Topic Name
          contentType: application/json
        event-out:
#<<< EDA / Topic Name
          destination: self
#>>> EDA / Topic Name
          contentType: application/json

logging:
  level:
    org.springframework.cloud: debug

# GitPod CORS 설정
management:
  endpoints:
    web:
      cors:
        allowed-origins: "*"
        allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
        allowed-headers: "*"

---

spring:
  profiles: docker
  cloud:
    stream:
      kafka:
        binder:
          brokers: my-kafka:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: point
          destination: self
          contentType: application/json
        event-out:
          destination: self
          contentType: application/json