# 기본 설정 (Docker 환경에서 사용)
server:
  port: 8080

spring:
  application:
    name: point

# Firebase 설정
firebase:
  secret-id: "firebase-adminsdk"
  project-id: "aivle-team0721" # 실제 프로젝트 ID로 변경해주세요

---

# 로컬 개발 환경 (default profile)
spring:
  profiles: default
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: point
          destination: self
          contentType: application/json
        event-out:
          destination: self
          contentType: application/json

logging:
  level:
    org.springframework.cloud: debug

management:
  endpoints:
    web:
      cors:
        allowed-origins: "*"
        allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
        allowed-headers: "*"

server:
  port: 8085 # 로컬 개발용 포트

---

# Docker 환경 (docker profile)
spring:
  profiles: docker
  cloud:
    stream:
      kafka:
        binder:
          brokers: my-kafka:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: point
          destination: self
          contentType: application/json
        event-out:
          destination: self
          contentType: application/json
